### PR TITLE
Added Calculation

### PR DESCRIPTION
**Pull request by aparna03dubey**
Updated the code

### CODE REVIEW

**Comment by ArthPatel02** [comment]
Check the values of A and B.

**Comment by aparna03dubey** [comment]
Pls check. @ArthPatel02

**Comment by ArthPatel02** [comment]
Go to Value.md file and check the values again.

**Comment by aparna03dubey** [comment]
Done.

**Comment by ArthPatel02** [comment]
Happy learning 🩵 !!

**Pull request merged**
